version: "2"
services:
  node:
    image: "node:18.17"
    user: "node"
    working_dir: /home/nespoli/Progetti/Uni/cose_vere/esami/
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/nespoli/Progetti/Uni/cose_vere/esami/
    expose:
      - "8080"
    command: "yarn start"
